# Generated by Django 5.2.6 on 2025-10-30 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_employer_profile_photo'),
        ('systemlogs', '0002_aidocumentcheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aidocumentcheck',
            old_name='ai_confidence',
            new_name='confidence_score',
        ),
        migrations.RenameField(
            model_name='aidocumentcheck',
            old_name='reason',
            new_name='detected_text',
        ),
        migrations.RenameField(
            model_name='aidocumentcheck',
            old_name='doc_type',
            new_name='document_type',
        ),
        migrations.RemoveField(
            model_name='aidocumentcheck',
            name='status',
        ),
        migrations.RemoveField(
            model_name='aidocumentcheck',
            name='user',
        ),
        migrations.AddField(
            model_name='aidocumentcheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidocumentcheck',
            name='jobseeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ai_document_checks', to='accounts.jobseeker'),
            preserve_default=False,
        ),
    ]
