# Generated by Django 5.2.6 on 2025-10-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemlogs', '0003_rename_ai_confidence_aidocumentcheck_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidocumentcheck',
            name='status',
            field=models.CharField(choices=[('Flagged', 'Flagged'), ('Cleared', 'Cleared'), ('Rejected', 'Rejected')], default='Flagged', max_length=20),
        ),
    ]
