# Generated by Django 5.2.6 on 2025-10-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_employer_barangay_clearance_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'db_table': 'applications_application',
                'managed': True,
            },
        ),
    ]
