# Generated by Django 5.2.6 on 2025-10-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=8, null=True),
        ),
    ]
