# Generated by Django 5.2.6 on 2025-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
