# Generated by Django 5.2.6 on 2025-10-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employer_bio_employer_personal_address_and_more'),
        ('jobs', '0002_job_experience_required_job_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Maintenance', 'Maintenance'), ('Transportation', 'Transportation'), ('Hospitality', 'Hospitality'), ('Customer Service', 'Customer Service'), ('Warehouse', 'Warehouse'), ('Driver', 'Driver'), ('Technician', 'Technician'), ('Electrician', 'Electrician'), ('Mechanic', 'Mechanic'), ('Laborer', 'Laborer'), ('Other', 'Other')], default='Other', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Surigao City', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.employer'),
        ),
    ]
