# Generated by Django 5.2.6 on 2025-10-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employer_bio_employer_personal_address_and_more'),
        ('jobs', '0003_remove_job_experience_required_remove_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.employer'),
        ),
    ]
