# Generated by Django 5.2.6 on 2025-10-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_notification_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
