# Generated by Django 5.2.6 on 2025-11-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_application_status_alter_notification_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Maintenance', 'Maintenance'), ('Transportation', 'Transportation'), ('Plumber', 'Plumber'), ('Customer Service', 'Customer Service'), ('Carpentry', 'Carpentry'), ('Driver', 'Driver'), ('Technician', 'Technician'), ('Electrician', 'Electrician'), ('Mechanic', 'Mechanic'), ('Laborer', 'Laborer'), ('Other', 'Other')], max_length=100),
        ),
    ]
