# Generated by Django 5.2.6 on 2025-11-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
