# Generated by Django 5.2.6 on 2025-11-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_close_on_quota',
            field=models.BooleanField(default=True, help_text='Automatically mark unavailable when quota is reached'),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_quota',
            field=models.PositiveIntegerField(default=1, help_text='Number of workers needed'),
        ),
    ]
