# Generated by Django 5.2.6 on 2025-11-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_auto_close_on_quota_job_hiring_quota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='jobseeker',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='applied_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
