# Generated by Django 5.2.6 on 2025-11-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_rename_jobseeker_application_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='auto_close_on_quota',
        ),
        migrations.RemoveField(
            model_name='job',
            name='hiring_quota',
        ),
    ]
