# Generated by Django 5.2.6 on 2025-11-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_job_auto_close_on_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_close_on_quota',
            field=models.BooleanField(default=False, help_text='Automatically mark as unavailable when quota is met'),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_quota',
            field=models.IntegerField(default=1, help_text='Number of workers to hire'),
        ),
    ]
