# Generated by Django 5.2.6 on 2025-11-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_auto_close_on_quota_job_hiring_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, help_text='Applications will close automatically after this date/time', null=True),
        ),
    ]
