# Generated by Django 5.2.6 on 2025-11-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_application_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], help_text='Employment type (Full-time, Part-time, etc.)', max_length=50, null=True),
        ),
    ]
