# Generated by Django 5.2.6 on 2025-11-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Commission', 'Commission')], help_text='Employment type (Full-time, Part-time, or Commission-based)', max_length=50, null=True),
        ),
    ]
