# Generated by Django 5.2.6 on 2026-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Hired', 'Hired'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Not Completed', 'Not Completed')], default='Pending', max_length=20),
        ),
    ]
