# Generated by Django 5.2.6 on 2025-10-21 11:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone_otp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('JobSeeker', 'Job Seeker'), ('Employer', 'Employer'), ('Admin', 'System Admin')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('email_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('employer_type', models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Company', 'Company')], default='Personal', max_length=20, null=True)),
                ('profile_completion', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('business_permit', models.FileField(blank=True, null=True, upload_to='company_docs/permits/')),
                ('company_id_file', models.FileField(blank=True, null=True, upload_to='company_docs/ids/')),
                ('valid_id', models.FileField(blank=True, null=True, upload_to='personal_docs/ids/')),
                ('barangay_clearance', models.FileField(blank=True, null=True, upload_to='personal_docs/barangay/')),
                ('police_clearance', models.FileField(blank=True, null=True, upload_to='personal_docs/police/')),
                ('nbi_clearance', models.FileField(blank=True, null=True, upload_to='personal_docs/nbi/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerDocuments',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('document_file', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_documents', to='accounts.employer')),
            ],
            options={
                'verbose_name_plural': 'Employer Documents',
                'db_table': 'employerdocuments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('seeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('barangay_clearance', models.FileField(blank=True, null=True, upload_to='clearances/barangay/')),
                ('police_clearance', models.FileField(blank=True, null=True, upload_to='clearances/police/')),
                ('nbi_clearance', models.FileField(blank=True, null=True, upload_to='clearances/nbi/')),
                ('nc2_certificate', models.FileField(blank=True, null=True, upload_to='certificates/nc2/')),
                ('valid_id_type', models.CharField(blank=True, choices=[('PhilHealth', 'PhilHealth ID'), ('SSS', 'SSS ID'), ('Pag-IBIG', 'Pag-IBIG ID'), ("Driver's License", "Driver's License"), ('National ID', 'National ID'), ('Passport', 'Passport')], max_length=100, null=True)),
                ('valid_id', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('verification_status', models.CharField(default='Pending', max_length=50)),
                ('profile_completion', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Seekers',
                'db_table': 'jobseeker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobSeekerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'systemlog',
                'managed': True,
            },
        ),
    ]
