# Generated by Django 5.2.6 on 2025-10-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sync_users_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='barangay_clearance',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='nbi_clearance',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='police_clearance',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='valid_id',
        ),
        migrations.AddField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterModelTable(
            name='employer',
            table='employers',
        ),
    ]
