# Generated by Django 5.2.6 on 2025-10-24 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employer_barangay_clearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='barangay_clearance',
            field=models.FileField(blank=True, null=True, upload_to='employer_docs/barangay/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='employer',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to='employer_docs/nbi/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='employer',
            name='police_clearance',
            field=models.FileField(blank=True, null=True, upload_to='employer_docs/police/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Optional for personal employers.', null=True, upload_to='company_docs/permits/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_id_file',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/ids/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterModelTable(
            name='employer',
            table=None,
        ),
    ]
