# Generated by Django 5.2.6 on 2025-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employer_barangay_clearance_employer_nbi_clearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='certifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_job_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
