# Generated by Django 5.2.6 on 2025-10-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_documentverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='personal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='barangay_clearance',
            field=models.FileField(blank=True, null=True, upload_to='employer_docs/barangay/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='business_permit',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/permits/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_id_file',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/ids/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to='employer_docs/nbi/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='police_clearance',
            field=models.FileField(blank=True, null=True, upload_to='employer_docs/police/'),
        ),
    ]
