# Generated by Django 5.2.6 on 2025-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employer_bio_employer_personal_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Maintenance', 'Maintenance'), ('Transportation', 'Transportation'), ('Hospitality', 'Hospitality'), ('Customer Service', 'Customer Service'), ('Warehouse', 'Warehouse'), ('Driver', 'Driver'), ('Technician', 'Technician'), ('Electrician', 'Electrician'), ('Mechanic', 'Mechanic'), ('Laborer', 'Laborer'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
