# Generated by Django 5.2.6 on 2025-10-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_jobseeker_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='preferred_job_types',
        ),
    ]
