# Generated by Django 5.2.6 on 2025-10-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_jobseeker_preferred_job_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_job_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
