# Generated by Django 5.2.6 on 2025-10-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jobseeker_preferred_job_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
