# Generated by Django 5.2.6 on 2025-10-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_jobseeker_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_photos/'),
        ),
    ]
