# Generated by Django 5.2.6 on 2025-10-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_employer_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
