# Generated by Django 5.2.6 on 2025-11-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Maintenance', 'Maintenance'), ('Transportation', 'Transportation'), ('Plumber', 'Plumber'), ('Customer Service', 'Customer Service'), ('Carpentry', 'Carpentry'), ('Driver', 'Driver'), ('Technician', 'Technician'), ('Electrician', 'Electrician'), ('Mechanic', 'Mechanic'), ('Laborer', 'Laborer'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='valid_id_type',
            field=models.CharField(blank=True, choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Driver’s License', 'Driver’s License'), ('UMID', 'UMID'), ('Voter’s ID', 'Voter’s ID'), ('PhilHealth', 'PhilHealth')], max_length=100, null=True),
        ),
    ]
