# Generated by Django 5.2.6 on 2025-11-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_jobseeker_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='valid_id',
            field=models.FileField(blank=True, null=True, upload_to='employer_docs/valid_id/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='valid_id_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
