# Generated by Django 5.2.6 on 2025-11-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_employer_valid_id_employer_valid_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='barangay_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='business_permit_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_id_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='nbi_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='police_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='valid_id_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
