# Generated by Django 5.2.6 on 2025-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_employer_barangay_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
