# Generated by Django 5.2.6 on 2025-11-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_employer_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
