# Generated by Django 5.2.6 on 2025-11-15 03:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_jobseeker_contact_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='valid_id_type',
            field=models.CharField(blank=True, choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ("Driver's License", "Driver's License"), ('UMID', 'UMID'), ("Voter's ID", "Voter's ID"), ('PhilHealth', 'PhilHealth')], max_length=100, null=True),
        ),
    ]
