# Generated by Django 5.2.6 on 2025-11-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_users_managers_alter_jobseeker_valid_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('JobSeeker', 'Job Seeker'), ('Employer', 'Employer'), ('Admin', 'System Admin')], max_length=20, null=True),
        ),
    ]
