# Generated by Django 5.2.6 on 2025-11-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='barangay_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='business_permit_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_id_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='nbi_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='police_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='valid_id_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
