# Generated by Django 5.2.6 on 2025-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_employer_barangay_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='valid_id_back',
            field=models.FileField(blank=True, null=True, upload_to='ids/'),
        ),
    ]
