# Generated by Django 5.2.6 on 2025-11-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_jobseeker_valid_id_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='valid_id_back',
            field=models.FileField(blank=True, null=True, upload_to='employer_docs/valid_id/'),
        ),
    ]
